'use client';

import { useState, useMemo, useRef, useEffect } from 'react';
import { format, parseISO } from 'date-fns';
import type { Site, Cleaner, ActionPlan, ActionPlanTask } from '@/lib/data';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { DatePicker } from '@/components/ui/date-picker';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { PlusCircle, FileDown, RefreshCw, Trash2, FileSpreadsheet } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogClose, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from '@/hooks/use-toast';


function PrintableActionPlan({ plan, forwardedRef }: { plan: ActionPlan, forwardedRef: React.Ref<HTMLDivElement> }) {
  return (
    <div ref={forwardedRef} className="p-8 bg-white text-black" style={{ width: '794px', minHeight: '1123px' }}>
      <h1 className="text-3xl font-bold mb-2 border-b-2 border-black pb-2">Action Plan</h1>
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-semibold">{plan.targetName}</h2>
        <span className="text-lg capitalize font-medium bg-gray-200 px-3 py-1 rounded">{plan.targetType}</span>
      </div>

      {plan.tasks.length > 0 && (
        <div className="mb-6">
            <h3 className="text-xl font-bold mb-3 border-b border-gray-400 pb-1">Action Items</h3>
            <div className="space-y-6">
                {plan.tasks.map(task => (
                    <div key={task.id} className="break-inside-avoid">
                        <div className="pl-4 border-l-4 border-gray-300">
                            <p className="font-semibold text-lg">{task.description}</p>
                            <p className="text-base text-gray-600">
                                Due: {format(parseISO(task.dueDate), 'PPP')} | Status: <span className={`font-semibold ${task.completed ? 'text-green-700' : 'text-red-700'}`}>{task.completed ? 'Completed' : 'Pending'}</span>
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
      )}

      {plan.notes && (
        <div>
          <h3 className="text-xl font-bold mb-3 border-b border-gray-400 pb-1">Notes</h3>
          <p className="text-base whitespace-pre-wrap">{plan.notes}</p>
        </div>
      )}
      
      <div style={{ position: 'absolute', bottom: '20px', left: '20px', right: '20px', textAlign: 'center', fontSize: '10px', color: '#888' }}>
        Report Generated by Excellerate Services on {format(new Date(), 'PPP')}
      </div>
    </div>
  );
}


function ActionPlanDetails({ item, plan: initialPlan, onUpdateActionPlan, onRemoveActionPlan }: { item: {id: string, name: string, type: 'site' | 'cleaner'}, plan: ActionPlan, onUpdateActionPlan: (plan: ActionPlan) => void, onRemoveActionPlan: (planId: string) => void }) {
  const plan = useMemo(() => initialPlan || { id: item.id, targetName: item.name, targetType: item.type, tasks: [], notes: '' }, [initialPlan, item]);
  
  const [newTaskDesc, setNewTaskDesc] = useState('');
  const [newTaskDueDate, setNewTaskDueDate] = useState<Date | undefined>();
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [isGeneratingExcel, setIsGeneratingExcel] = useState(false);
  const printableRef = useRef<HTMLDivElement>(null);

  const handleUpdate = (updatedPlan: Partial<Omit<ActionPlan, 'id'>>) => {
    onUpdateActionPlan({ ...plan, ...updatedPlan });
  };

  const handleAddTask = () => {
    if (!newTaskDesc || !newTaskDueDate) return;
    const newTask: ActionPlanTask = {
      id: `task-${Date.now()}`,
      description: newTaskDesc,
      dueDate: format(newTaskDueDate, 'yyyy-MM-dd'),
      completed: false,
    };
    handleUpdate({ tasks: [...plan.tasks, newTask] });
    setNewTaskDesc('');
    setNewTaskDueDate(undefined);
  };

  const handleToggleTask = (taskId: string) => {
    const updatedTasks = plan.tasks.map(task =>
      task.id === taskId ? { ...task, completed: !task.completed } : task
    );
    handleUpdate({ tasks: updatedTasks });
  };
  
  const handleNotesChange = (notes: string) => {
      handleUpdate({ notes });
  }

  const handleShareOnWhatsApp = () => {
    let message = `*Action Plan: ${plan.targetName}*\n\n`;

    if (plan.tasks.length > 0) {
        message += "*Tasks:*\n";
        plan.tasks.forEach(task => {
            const status = task.completed ? '✅' : '🔲';
            message += `${status} ${task.description} (Due: ${format(parseISO(task.dueDate), 'PP')})\n`;
        });
        message += "\n";
    }

    if (plan.notes) {
        message += `*Notes:*\n${plan.notes}\n`;
    }

    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  const handleGeneratePdf = async () => {
    if (!printableRef.current) return;
    setIsGeneratingPdf(true);

    try {
      const { default: jsPDF } = await import('jspdf');
      const { default: html2canvas } = await import('html2canvas');
      
      const canvas = await html2canvas(printableRef.current, {
        scale: 2,
      });
      const imgData = canvas.toDataURL('image/png');

      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();

      const canvasWidth = canvas.width;
      const canvasHeight = canvas.height;
      const ratio = canvasWidth / canvasHeight;
      
      let imgWidthInPdf = pdfWidth - 20;
      let imgHeightInPdf = imgWidthInPdf / ratio;
      
      if (imgHeightInPdf > pdfHeight - 20) {
        imgHeightInPdf = pdfHeight - 20;
        imgWidthInPdf = imgHeightInPdf * ratio;
      }

      const x = (pdfWidth - imgWidthInPdf) / 2;
      const y = 10;

      pdf.addImage(imgData, 'PNG', x, y, imgWidthInPdf, imgHeightInPdf);
      pdf.save(`Action_Plan_${plan.targetName.replace(/\s+/g, '_')}.pdf`);

    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleGenerateExcel = async () => {
    if (!plan) return;
    setIsGeneratingExcel(true);
    try {
        const XLSX = await import('xlsx');

        const header = ["Task Description", "Due Date", "Status"];
        const tasksData = plan.tasks.map(task => ([
            task.description,
            format(parseISO(task.dueDate), 'yyyy-MM-dd'),
            task.completed ? 'Completed' : 'Pending',
        ]));

        const finalData = [
            ["Action Plan for:", plan.targetName, `(${plan.targetType})`],
            [],
            header,
            ...tasksData,
            [],
            ["Notes:"],
            [plan.notes || ''],
        ];

        const worksheet = XLSX.utils.aoa_to_sheet(finalData);

        worksheet['!cols'] = [ { wch: 50 }, { wch: 20 }, { wch: 15 } ];

        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, 'Action Plan');

        XLSX.writeFile(workbook, `Action_Plan_${plan.targetName.replace(/\s+/g, '_')}.xlsx`);
    } catch (error) {
        console.error("Error generating Excel:", error);
    } finally {
        setIsGeneratingExcel(false);
    }
  };

  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
          <PrintableActionPlan plan={plan} forwardedRef={printableRef} />
      </div>
      <div className="space-y-4 pl-4 border-l-2">
        <div className="space-y-2">
          <h4 className="font-semibold mb-2">Tasks</h4>
          <div className="space-y-2">
            {plan.tasks.length > 0 ? (
                <div className="space-y-2">
                    {plan.tasks.map(task => (
                      <div key={task.id} className="flex items-center gap-3 p-2 border rounded-md">
                        <Checkbox
                          id={`task-${task.id}`}
                          checked={task.completed}
                          onCheckedChange={() => handleToggleTask(task.id)}
                        />
                        <Label
                          htmlFor={`task-${task.id}`}
                          className={`flex-1 cursor-pointer ${task.completed ? 'line-through text-muted-foreground' : ''}`}
                        >
                          {task.description}
                          <span className="text-xs text-muted-foreground ml-2">
                            (Due: {format(parseISO(task.dueDate), 'PP')})
                          </span>
                        </Label>
                      </div>
                    ))}
                </div>
            ) : <p className="text-sm text-muted-foreground">No tasks added yet.</p>}
        </div>
        </div>

        <div className="space-y-2">
          <h4 className="font-semibold">Add New Task</h4>
          <div className="flex flex-col sm:flex-row gap-2">
            <Input
              placeholder="Task description"
              value={newTaskDesc}
              onChange={e => setNewTaskDesc(e.target.value)}
              className="flex-grow"
            />
            <DatePicker
              date={newTaskDueDate}
              onDateChange={setNewTaskDueDate}
              modal={true}
              placeholder="Select due date"
              className="w-full sm:w-[200px]"
            />
            <Button onClick={handleAddTask} size="sm">
              <PlusCircle className="mr-2 h-4 w-4" />
              Add
            </Button>
          </div>
        </div>

        <div>
          <h4 className="font-semibold mb-2">Notes</h4>
          <Textarea
            placeholder="Add general notes for the action plan..."
            value={plan.notes || ''}
            onChange={e => handleNotesChange(e.target.value)}
            className="min-h-[80px]"
          />
        </div>

        <div className="flex justify-end pt-4 border-t mt-4 gap-2">
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button variant="destructive" className="mr-auto">
                  <Trash2 className="mr-2 h-4 w-4" /> Delete Plan
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This will permanently delete the action plan for {plan.targetName}. This action cannot be undone.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={() => onRemoveActionPlan(plan.id)}>Delete</AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          <Button onClick={handleShareOnWhatsApp} variant="outline">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
              WhatsApp
          </Button>
          <Button onClick={handleGenerateExcel} disabled={isGeneratingExcel} variant="outline">
            {isGeneratingExcel ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-2 h-4 w-4" />}
            {isGeneratingExcel ? 'Generating...' : 'Export Excel'}
          </Button>
          <Button onClick={handleGeneratePdf} disabled={isGeneratingPdf}>
            {isGeneratingPdf ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileDown className="mr-2 h-4 w-4" />}
            {isGeneratingPdf ? 'Generating...' : 'Download PDF'}
          </Button>
        </div>
      </div>
    </>
  );
}

interface CreateActionPlanDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  sites: Site[];
  cleaners: Cleaner[];
  existingPlanIds: string[];
  onCreatePlan: (plan: ActionPlan) => void;
}

function CreateActionPlanDialog({ open, onOpenChange, sites, cleaners, existingPlanIds, onCreatePlan }: CreateActionPlanDialogProps) {
  const [targetType, setTargetType] = useState<'site' | 'cleaner'>('site');
  const [targetId, setTargetId] = useState('');
  const { toast } = useToast();

  const targets = targetType === 'site' ? sites : cleaners;
  
  const handleCreate = () => {
    if (!targetId) {
      toast({ variant: 'destructive', title: 'Please select a target.' });
      return;
    }
    if (existingPlanIds.includes(targetId)) {
      toast({ variant: 'destructive', title: 'Action plan already exists for this target.' });
      return;
    }
    const target = targets.find(t => t.id === targetId);
    if (!target) return;

    onCreatePlan({
      id: target.id,
      targetName: target.name,
      targetType: targetType,
      tasks: [],
      notes: ''
    });
    toast({ title: 'Action Plan Created', description: `You can now add tasks and notes for ${target.name}.`});
    onOpenChange(false);
  };

  useEffect(() => {
    if (open) {
      setTargetType('site');
      setTargetId('');
    }
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create New Action Plan</DialogTitle>
          <DialogDescription>Select a site or cleaner to create an action plan for.</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label>Target Type</Label>
            <Select value={targetType} onValueChange={(v: 'site' | 'cleaner') => { setTargetType(v); setTargetId(''); }}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="site">Site</SelectItem>
                <SelectItem value="cleaner">Cleaner</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label>Target</Label>
            <Select value={targetId} onValueChange={setTargetId}>
              <SelectTrigger><SelectValue placeholder={`Select a ${targetType}`} /></SelectTrigger>
              <SelectContent>
                {targets.map(t => (
                  <SelectItem key={t.id} value={t.id} disabled={existingPlanIds.includes(t.id)}>
                    {t.name} {existingPlanIds.includes(t.id) && '(Has Plan)'}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
        <DialogFooter>
          <DialogClose asChild><Button variant="ghost">Cancel</Button></DialogClose>
          <Button onClick={handleCreate}>Create</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}


interface ActionPlanTabProps {
  sites: Site[];
  cleaners: Cleaner[];
  actionPlans: ActionPlan[];
  onUpdateActionPlan: (plan: ActionPlan) => void;
  onRemoveActionPlan: (planId: string) => void;
}

export default function ActionPlanTab({ sites, cleaners, actionPlans, onUpdateActionPlan, onRemoveActionPlan }: ActionPlanTabProps) {
  const sortedSites = useMemo(() => sites ? [...sites].sort((a, b) => a.name.localeCompare(b.name)) : [], [sites]);
  const sortedCleaners = useMemo(() => cleaners ? [...cleaners].sort((a, b) => a.name.localeCompare(b.name)) : [], [cleaners]);
  
  const [isGeneratingAllPdf, setIsGeneratingAllPdf] = useState(false);
  const [isGeneratingAllExcel, setIsGeneratingAllExcel] = useState(false);
  const [isCreateDialogOpen, setCreateDialogOpen] = useState(false);

  const existingActionPlans = useMemo(() => {
    return [...actionPlans].sort((a, b) => a.targetName.localeCompare(b.targetName));
  }, [actionPlans]);

  const printableRefs = useRef<(HTMLDivElement | null)[]>([]);
  useEffect(() => {
    printableRefs.current = printableRefs.current.slice(0, existingActionPlans.length);
  }, [existingActionPlans]);

  const handleShareAllOnWhatsApp = () => {
    let fullMessage = `*All Action Plans Report*\nGenerated on: ${format(new Date(), 'PPP')}\n\n`;
    
    existingActionPlans.forEach((plan) => {
        fullMessage += `------------------------------------\n`;
        fullMessage += `*Action Plan for: ${plan.targetName} (${plan.targetType})*\n\n`;

        if (plan.tasks.length > 0) {
            fullMessage += "*Tasks:*\n";
            plan.tasks.forEach(task => {
                const status = task.completed ? '✅' : '🔲';
                fullMessage += `${status} ${task.description} (Due: ${format(parseISO(task.dueDate), 'PP')})\n`;
            });
            fullMessage += "\n";
        } else {
            fullMessage += "_No tasks for this plan._\n\n";
        }

        if (plan.notes) {
            fullMessage += `*Notes:*\n${plan.notes}\n`;
        }
        
        fullMessage += `\n`;
    });
    
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(fullMessage)}`;
    window.open(whatsappUrl, '_blank');
  };

  const handleGenerateAllPdfs = async () => {
    if (printableRefs.current.length === 0) return;
    setIsGeneratingAllPdf(true);
    try {
        const { default: jsPDF } = await import('jspdf');
        const { default: html2canvas } = await import('html2canvas');
        
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();

        for (let i = 0; i < printableRefs.current.length; i++) {
            const element = printableRefs.current[i];
            if (element) {
                 const canvas = await html2canvas(element, { scale: 2 });
                const imgData = canvas.toDataURL('image/png');

                const canvasWidth = canvas.width;
                const canvasHeight = canvas.height;
                const ratio = canvasWidth / canvasHeight;
                
                let imgWidthInPdf = pdfWidth - 20;
                let imgHeightInPdf = imgWidthInPdf / ratio;
                
                if (imgHeightInPdf > pdfHeight - 20) {
                  imgHeightInPdf = pdfHeight - 20;
                  imgWidthInPdf = imgHeightInPdf * ratio;
                }

                const x = (pdfWidth - imgWidthInPdf) / 2;
                const y = 10;

                if (i > 0) {
                    pdf.addPage();
                }
                pdf.addImage(imgData, 'PNG', x, y, imgWidthInPdf, imgHeightInPdf);
            }
        }
        pdf.save('All_Action_Plans.pdf');
    } catch (error) {
        console.error("Error generating all PDFs:", error);
    } finally {
        setIsGeneratingAllPdf(false);
    }
  };

  const handleGenerateAllExcel = async () => {
    if (existingActionPlans.length === 0) return;
    setIsGeneratingAllExcel(true);
    try {
        const XLSX = await import('xlsx');
        
        const allData: (string | number | Date | null)[][] = [];
        allData.push(['Target', 'Type', 'Task', 'Due Date', 'Status', 'Notes']);

        existingActionPlans.forEach(plan => {
            allData.push([plan.targetName, plan.targetType, '---', '---', '---', plan.notes || '']);

            if (plan.tasks.length > 0) {
                plan.tasks.forEach(task => {
                    allData.push([
                        '',
                        '',
                        task.description,
                        format(parseISO(task.dueDate), 'yyyy-MM-dd'),
                        task.completed ? 'Completed' : 'Pending',
                        '',
                    ]);
                });
            }
            allData.push([]); // Spacer row
        });

        const ws = XLSX.utils.aoa_to_sheet(allData);
        ws['!cols'] = [ { wch: 30 }, { wch: 10 }, { wch: 50 }, { wch: 15 }, { wch: 15 }, { wch: 50 } ];
        
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'All Action Plans');
        XLSX.writeFile(wb, 'All_Action_Plans.xlsx');
    } catch (error) {
        console.error("Error generating all Excel files:", error);
    } finally {
        setIsGeneratingAllExcel(false);
    }
  };


  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
        {existingActionPlans.map((plan, index) => (
            <PrintableActionPlan key={plan.id} plan={plan} forwardedRef={el => {
                if (printableRefs.current) {
                    printableRefs.current[index] = el;
                }
            }} />
        ))}
      </div>
      <CreateActionPlanDialog
        open={isCreateDialogOpen}
        onOpenChange={setCreateDialogOpen}
        sites={sortedSites}
        cleaners={sortedCleaners}
        existingPlanIds={existingActionPlans.map(p => p.id)}
        onCreatePlan={onUpdateActionPlan}
      />
      <Card>
        <CardHeader>
          <div className="flex flex-col sm:flex-row gap-4 sm:items-start sm:justify-between">
            <div>
              <CardTitle>Action Plan Management</CardTitle>
              <CardDescription>Create and manage action plans for sites and cleaners.</CardDescription>
            </div>
             <div className="flex flex-wrap gap-2">
                <Button onClick={() => setCreateDialogOpen(true)}>
                    <PlusCircle className="mr-2 h-4 w-4" /> Create Action Plan
                </Button>
                <Button onClick={handleShareAllOnWhatsApp} variant="outline" disabled={existingActionPlans.length === 0}>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
                    Share All
                </Button>
                 <Button onClick={handleGenerateAllExcel} disabled={isGeneratingAllExcel || existingActionPlans.length === 0} variant="outline">
                    {isGeneratingAllExcel ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-2 h-4 w-4" />}
                    {isGeneratingAllExcel ? 'Generating...' : 'Export All (Excel)'}
                </Button>
                 <Button onClick={handleGenerateAllPdfs} disabled={isGeneratingAllPdf || existingActionPlans.length === 0}>
                    {isGeneratingAllPdf ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileDown className="mr-2 h-4 w-4" />}
                    {isGeneratingAllPdf ? 'Generating...' : 'Download All (PDF)'}
                </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {existingActionPlans.length === 0 ? (
            <div className="rounded-lg border-2 border-dashed bg-card text-card-foreground p-6 min-h-[200px] flex items-center justify-center">
              <p className="text-muted-foreground">No action plans have been created yet.</p>
            </div>
          ) : (
            <Accordion type="multiple" className="w-full space-y-2">
              {existingActionPlans.map(plan => (
                <AccordionItem key={plan.id} value={plan.id} className="border rounded-md px-4">
                  <AccordionTrigger className="hover:no-underline">
                      <div className="flex justify-between items-center w-full pr-2">
                          <span className="font-medium">{plan.targetName}</span>
                          <span className="text-sm text-muted-foreground capitalize bg-muted px-2 py-1 rounded-md">{plan.targetType}</span>
                      </div>
                  </AccordionTrigger>
                  <AccordionContent>
                    <ActionPlanDetails
                      item={{id: plan.id, name: plan.targetName, type: plan.targetType}}
                      plan={plan}
                      onUpdateActionPlan={onUpdateActionPlan}
                      onRemoveActionPlan={onRemoveActionPlan}
                    />
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          )}
        </CardContent>
      </Card>
    </>
  );
}
