'use client';

import { useState, useMemo, useRef, useEffect } from 'react';
import { format, parseISO } from 'date-fns';
import type { Site, Cleaner, ActionPlan, ActionPlanTask } from '@/lib/data';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { DatePicker } from '@/components/ui/date-picker';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PlusCircle, FileDown, RefreshCw } from 'lucide-react';

function PrintableActionPlan({ plan, forwardedRef }: { plan: ActionPlan, forwardedRef: React.Ref<HTMLDivElement> }) {
  return (
    <div ref={forwardedRef} className="p-8 bg-white text-black" style={{ width: '794px', minHeight: '1123px' }}>
      <h1 className="text-3xl font-bold mb-2 border-b-2 border-black pb-2">Action Plan</h1>
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-semibold">{plan.targetName}</h2>
        <span className="text-lg capitalize font-medium bg-gray-200 px-3 py-1 rounded">{plan.targetType}</span>
      </div>

      {plan.tasks.length > 0 && (
        <div className="mb-6">
            <h3 className="text-xl font-bold mb-3 border-b border-gray-400 pb-1">Action Items</h3>
            <div className="space-y-6">
                {plan.tasks.map(task => (
                    <div key={task.id} className="break-inside-avoid">
                        <div className="pl-4 border-l-4 border-gray-300">
                            <p className="font-semibold text-lg">{task.description}</p>
                            <p className="text-base text-gray-600">
                                Due: {format(parseISO(task.dueDate), 'PPP')} | Status: <span className={`font-semibold ${task.completed ? 'text-green-700' : 'text-red-700'}`}>{task.completed ? 'Completed' : 'Pending'}</span>
                            </p>
                        </div>
                        {(task.beforeImageUrl || task.afterImageUrl) && (
                            <div className="grid grid-cols-2 gap-4 mt-4 pl-4">
                                <div>
                                    <p className="text-sm font-bold mb-1">Before</p>
                                    {task.beforeImageUrl ? (
                                        <img src={task.beforeImageUrl} alt="Before" className="w-full h-auto rounded border" />
                                    ) : (
                                        <div className="border rounded h-32 flex items-center justify-center bg-gray-100 text-gray-500 text-sm">No Image</div>
                                    )}
                                </div>
                                <div>
                                    <p className="text-sm font-bold mb-1">After</p>
                                    {task.afterImageUrl ? (
                                        <img src={task.afterImageUrl} alt="After" className="w-full h-auto rounded border" />
                                    ) : (
                                        <div className="border rounded h-32 flex items-center justify-center bg-gray-100 text-gray-500 text-sm">No Image</div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
      )}

      {plan.notes && (
        <div>
          <h3 className="text-xl font-bold mb-3 border-b border-gray-400 pb-1">Notes</h3>
          <p className="text-base whitespace-pre-wrap">{plan.notes}</p>
        </div>
      )}
      
      <div style={{ position: 'absolute', bottom: '20px', left: '20px', right: '20px', textAlign: 'center', fontSize: '10px', color: '#888' }}>
        Report Generated by Excellerate Services on {format(new Date(), 'PPP')}
      </div>
    </div>
  );
}


function ActionPlanDetails({ item, plan: initialPlan, onUpdateActionPlan }: { item: {id: string, name: string, type: 'site' | 'cleaner'}, plan: ActionPlan | undefined, onUpdateActionPlan: (plan: ActionPlan) => void}) {
  // Ensure the plan always has an ID, using the item's ID if no plan exists yet.
  const plan = useMemo(() => initialPlan || { id: item.id, targetName: item.name, targetType: item.type, tasks: [], notes: '' }, [initialPlan, item]);
  
  const [newTaskDesc, setNewTaskDesc] = useState('');
  const [newTaskDueDate, setNewTaskDueDate] = useState<Date | undefined>();
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const printableRef = useRef<HTMLDivElement>(null);

  const handleUpdate = (updatedPlan: Partial<Omit<ActionPlan, 'id'>>) => {
    onUpdateActionPlan({ ...plan, ...updatedPlan });
  };

  const handleAddTask = () => {
    if (!newTaskDesc || !newTaskDueDate) return;
    const newTask: ActionPlanTask = {
      id: `task-${Date.now()}`,
      description: newTaskDesc,
      dueDate: format(newTaskDueDate, 'yyyy-MM-dd'),
      completed: false,
    };
    handleUpdate({ tasks: [...plan.tasks, newTask] });
    setNewTaskDesc('');
    setNewTaskDueDate(undefined);
  };

  const handleToggleTask = (taskId: string) => {
    const updatedTasks = plan.tasks.map(task =>
      task.id === taskId ? { ...task, completed: !task.completed } : task
    );
    handleUpdate({ tasks: updatedTasks });
  };
  
  const handleNotesChange = (notes: string) => {
      handleUpdate({ notes });
  }

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>, taskId: string, type: 'before' | 'after') => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onloadend = () => {
        const dataUrl = reader.result as string;
        const updatedTasks = plan.tasks.map(task => {
        if (task.id === taskId) {
            return {
            ...task,
            ...(type === 'before' ? { beforeImageUrl: dataUrl } : { afterImageUrl: dataUrl })
            };
        }
        return task;
        });
        handleUpdate({ tasks: updatedTasks });
    };
    reader.readAsDataURL(file);
  };

  const handleGeneratePdf = async () => {
    if (!printableRef.current) return;
    setIsGeneratingPdf(true);

    try {
      const { default: jsPDF } = await import('jspdf');
      const { default: html2canvas } = await import('html2canvas');
      
      const canvas = await html2canvas(printableRef.current, {
        scale: 2,
      });
      const imgData = canvas.toDataURL('image/png');

      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();

      const canvasWidth = canvas.width;
      const canvasHeight = canvas.height;
      const ratio = canvasWidth / canvasHeight;
      
      let imgWidthInPdf = pdfWidth - 20;
      let imgHeightInPdf = imgWidthInPdf / ratio;
      
      if (imgHeightInPdf > pdfHeight - 20) {
        imgHeightInPdf = pdfHeight - 20;
        imgWidthInPdf = imgHeightInPdf * ratio;
      }

      const x = (pdfWidth - imgWidthInPdf) / 2;
      const y = 10;

      pdf.addImage(imgData, 'PNG', x, y, imgWidthInPdf, imgHeightInPdf);
      pdf.save(`Action_Plan_${plan.targetName.replace(/\s+/g, '_')}.pdf`);

    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
          <PrintableActionPlan plan={plan} forwardedRef={printableRef} />
      </div>
      <div className="space-y-4 pl-4 border-l-2">
        <div>
          <h4 className="font-semibold mb-2">Tasks</h4>
          <div className="space-y-2">
            {plan.tasks.length > 0 ? (
                <Accordion type="multiple" className="space-y-1">
                    {plan.tasks.map(task => (
                        <AccordionItem value={task.id} key={task.id} className="border rounded-md">
                            <div className="flex items-center px-3">
                                <Checkbox
                                    id={`task-${task.id}`}
                                    checked={task.completed}
                                    onCheckedChange={() => handleToggleTask(task.id)}
                                />
                                <AccordionTrigger className="py-2 hover:no-underline flex-1 text-left">
                                    <div className={`ml-3 ${task.completed ? 'line-through text-muted-foreground' : ''}`}>
                                        {task.description}
                                        <span className="text-xs text-muted-foreground ml-2"> (Due: {format(parseISO(task.dueDate), 'PP')})</span>
                                    </div>
                                </AccordionTrigger>
                            </div>
                            <AccordionContent className="pl-12 pr-3">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                                    <div>
                                        <Label className="font-semibold">Before</Label>
                                        {task.beforeImageUrl ? (
                                            <img src={task.beforeImageUrl} alt="Before" className="mt-2 rounded-md border aspect-video object-cover w-full" />
                                        ) : (
                                            <div className="mt-2 aspect-video rounded-md border border-dashed flex items-center justify-center">
                                                <p className="text-muted-foreground text-sm">No image</p>
                                            </div>
                                        )}
                                        <Input 
                                            type="file" 
                                            accept="image/*" 
                                            onChange={(e) => handleImageUpload(e, task.id, 'before')} 
                                            className="mt-2 file:text-foreground file:text-xs file:sm:text-sm" 
                                        />
                                    </div>
                                    <div>
                                        <Label className="font-semibold">After</Label>
                                        {task.afterImageUrl ? (
                                            <img src={task.afterImageUrl} alt="After" className="mt-2 rounded-md border aspect-video object-cover w-full" />
                                        ) : (
                                            <div className="mt-2 aspect-video rounded-md border border-dashed flex items-center justify-center">
                                                <p className="text-muted-foreground text-sm">No image</p>
                                            </div>
                                        )}
                                        <Input 
                                            type="file" 
                                            accept="image/*" 
                                            onChange={(e) => handleImageUpload(e, task.id, 'after')} 
                                            className="mt-2 file:text-foreground file:text-xs file:sm:text-sm"
                                            disabled={!task.completed}
                                        />
                                    </div>
                                </div>
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            ) : <p className="text-sm text-muted-foreground">No tasks added yet.</p>}
        </div>
        </div>

        <div className="space-y-2">
          <h4 className="font-semibold">Add New Task</h4>
          <div className="flex flex-col sm:flex-row gap-2">
            <Input
              placeholder="Task description"
              value={newTaskDesc}
              onChange={e => setNewTaskDesc(e.target.value)}
              className="flex-grow"
            />
            <DatePicker
              date={newTaskDueDate}
              onDateChange={setNewTaskDueDate}
              modal={true}
              placeholder="Select due date"
              className="w-full sm:w-[200px]"
            />
            <Button onClick={handleAddTask} size="sm">
              <PlusCircle className="mr-2 h-4 w-4" />
              Add
            </Button>
          </div>
        </div>

        <div>
          <h4 className="font-semibold mb-2">Notes</h4>
          <Textarea
            placeholder="Add general notes for the action plan..."
            value={plan.notes || ''}
            onChange={e => handleNotesChange(e.target.value)}
            className="min-h-[80px]"
          />
        </div>

        <div className="flex justify-end pt-4 border-t mt-4">
          <Button onClick={handleGeneratePdf} disabled={isGeneratingPdf}>
            {isGeneratingPdf ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileDown className="mr-2 h-4 w-4" />}
            {isGeneratingPdf ? 'Generating...' : 'Download as PDF'}
          </Button>
        </div>
      </div>
    </>
  );
}

export default function ActionPlanTab({ sites, cleaners, actionPlans, onUpdateActionPlan }: ActionPlanTabProps) {
  const sortedSites = useMemo(() => sites ? [...sites].sort((a, b) => a.name.localeCompare(b.name)) : [], [sites]);
  const sortedCleaners = useMemo(() => cleaners ? [...cleaners].sort((a, b) => a.name.localeCompare(b.name)) : [], [cleaners]);
  const [isGeneratingAllPdf, setIsGeneratingAllPdf] = useState(false);
  const printableRefs = useRef<(HTMLDivElement | null)[]>([]);

  const actionItems = useMemo(() => {
    const siteItems = sortedSites
      .filter(s => s.status === 'Site under action plan' || s.status === 'Site requires action plan')
      .map(s => ({ id: s.id, name: s.name, type: 'site' as const }));

    const cleanerItems = sortedCleaners
      .filter(c => c.rating === 'Under action plan' || c.rating === 'Needs retraining')
      .map(c => ({ id: c.id, name: c.name, type: 'cleaner' as const }));

    return [...siteItems, ...cleanerItems].sort((a, b) => a.name.localeCompare(b.name));
  }, [sortedSites, sortedCleaners]);

  const allPlans = useMemo(() => {
    return actionItems.map(item => {
        return actionPlans.find(p => p.id === item.id) || { id: item.id, targetName: item.name, targetType: item.type, tasks: [], notes: '' };
    });
  }, [actionItems, actionPlans]);
  
  useEffect(() => {
    printableRefs.current = printableRefs.current.slice(0, allPlans.length);
  }, [allPlans]);

  const handleGenerateAllPdfs = async () => {
    if (printableRefs.current.length === 0) return;
    setIsGeneratingAllPdf(true);
    try {
        const { default: jsPDF } = await import('jspdf');
        const { default: html2canvas } = await import('html2canvas');
        
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();

        for (let i = 0; i < printableRefs.current.length; i++) {
            const element = printableRefs.current[i];
            if (element) {
                 const canvas = await html2canvas(element, { scale: 2 });
                const imgData = canvas.toDataURL('image/png');

                const canvasWidth = canvas.width;
                const canvasHeight = canvas.height;
                const ratio = canvasWidth / canvasHeight;
                
                let imgWidthInPdf = pdfWidth - 20;
                let imgHeightInPdf = imgWidthInPdf / ratio;
                
                if (imgHeightInPdf > pdfHeight - 20) {
                  imgHeightInPdf = pdfHeight - 20;
                  imgWidthInPdf = imgHeightInPdf * ratio;
                }

                const x = (pdfWidth - imgWidthInPdf) / 2;
                const y = 10;

                if (i > 0) {
                    pdf.addPage();
                }
                pdf.addImage(imgData, 'PNG', x, y, imgWidthInPdf, imgHeightInPdf);
            }
        }
        pdf.save('All_Action_Plans.pdf');
    } catch (error) {
        console.error("Error generating all PDFs:", error);
    } finally {
        setIsGeneratingAllPdf(false);
    }
  };


  if (actionItems.length === 0) {
    return (
      <div className="rounded-lg border bg-card text-card-foreground p-6 min-h-[200px] flex items-center justify-center">
        <p className="text-muted-foreground">No sites or cleaners currently require an action plan.</p>
      </div>
    );
  }

  return (
    <>
      <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
        {allPlans.map((plan, index) => (
            <PrintableActionPlan key={plan.id} plan={plan} forwardedRef={el => {
                if (printableRefs.current) {
                    printableRefs.current[index] = el;
                }
            }} />
        ))}
      </div>
      <Card>
        <CardHeader>
          <div className="flex flex-col sm:flex-row gap-4 sm:items-start sm:justify-between">
            <div>
              <CardTitle>Action Plan Management</CardTitle>
              <p className="text-sm text-muted-foreground">Sites and cleaners that require an action plan.</p>
            </div>
             <Button onClick={handleGenerateAllPdfs} disabled={isGeneratingAllPdf || actionItems.length === 0}>
                {isGeneratingAllPdf ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileDown className="mr-2 h-4 w-4" />}
                {isGeneratingAllPdf ? 'Generating...' : 'Download All'}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <Accordion type="multiple" className="w-full space-y-2">
            {actionItems.map(item => (
              <AccordionItem key={item.id} value={item.id} className="border rounded-md px-4">
                <AccordionTrigger className="hover:no-underline">
                    <div className="flex justify-between items-center w-full pr-2">
                        <span className="font-medium">{item.name}</span>
                        <span className="text-sm text-muted-foreground capitalize bg-muted px-2 py-1 rounded-md">{item.type}</span>
                    </div>
                </AccordionTrigger>
                <AccordionContent>
                  <ActionPlanDetails
                    item={item}
                    plan={actionPlans.find(p => p.id === item.id)}
                    onUpdateActionPlan={onUpdateActionPlan}
                  />
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </CardContent>
      </Card>
    </>
  );
}
