'use client';

import { useState, useMemo, ReactNode, useRef } from 'react';
import type { Site, MonthlyAudit, Appointment, Leave, ScheduleEntry } from '@/lib/data';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { format, parseISO, addDays, addWeeks, addMonths, addYears, startOfDay } from 'date-fns';
import { PlusCircle, Pencil, Trash2, Calendar, Briefcase, FileDown, RefreshCw, Users } from 'lucide-react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { cn } from '@/lib/utils';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AppointmentDialog } from './appointment-dialog';
import { Input } from './ui/input';
import { Label } from './ui/label';

// Event type for combined view
type DiaryEvent = {
    id: string;
    type: 'audit' | 'appointment' | 'cover';
    date: Date;
    title: string;
    details: string;
    site?: string;
    notes?: string;
    assignee: string;
    raw: Appointment | MonthlyAudit | (Leave & { site: string });
};


function PrintableDiary({ events, title, forwardedRef }: { events: DiaryEvent[], title: string, forwardedRef: React.Ref<HTMLDivElement> }) {
  const groupedEvents = events.reduce((acc, event) => {
      const day = format(event.date, 'yyyy-MM-dd');
      if (!acc[day]) acc[day] = [];
      acc[day].push(event);
      return acc;
  }, {} as Record<string, DiaryEvent[]>);
  const sortedDays = Object.keys(groupedEvents).sort();

  return (
      <div ref={forwardedRef} className="p-8 bg-white text-black" style={{ width: '794px', minHeight: '1123px' }}>
          <h1 className="text-3xl font-bold mb-2 border-b-2 border-black pb-2">{title}</h1>
          <p className="text-lg mb-6">{format(new Date(), 'PPP')}</p>

          {sortedDays.length > 0 ? sortedDays.map(day => (
              <div key={day} className="mb-6">
                  <h3 className="text-xl font-bold mb-3 border-b border-gray-400 pb-1">{format(parseISO(day), 'EEEE, do MMMM yyyy')}</h3>
                  <div className="space-y-4">
                      {groupedEvents[day].map(event => (
                          <div key={event.id}>
                              <p className="font-semibold text-lg">{event.title}{event.site && ` @ ${event.site}`}</p>
                              <p className="text-gray-700">{event.details}</p>
                              {event.notes && <p className="text-gray-600 italic pl-4">"{event.notes}"</p>}
                          </div>
                      ))}
                  </div>
              </div>
          )) : <p>No events scheduled.</p>}
          
          <div style={{ position: 'absolute', bottom: '20px', left: '20px', right: '20px', textAlign: 'center', fontSize: '10px', color: '#888' }}>
              Report Generated by Excellerate Services
          </div>
      </div>
  );
}

interface DiaryTabProps {
  sites: Site[];
  appointments: Appointment[];
  monthlyAudits: MonthlyAudit[];
  leave: Leave[];
  schedule: ScheduleEntry[];
  onAddAppointment: (data: Omit<Appointment, 'id'>) => void;
  onUpdateAppointment: (id: string, data: Partial<Omit<Appointment, 'id'>>) => void;
  onRemoveAppointment: (id: string) => void;
}

export default function DiaryTab({ sites, appointments, monthlyAudits, leave, schedule, onAddAppointment, onUpdateAppointment, onRemoveAppointment }: DiaryTabProps) {
    const [filterStartDate, setFilterStartDate] = useState<string>(format(new Date(), 'yyyy-MM-dd'));
    const [filterEndDate, setFilterEndDate] = useState<string>(format(new Date(), 'yyyy-MM-dd'));
    const [activeDiary, setActiveDiary] = useState('Manager');
    const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
    const printableRef = useRef<HTMLDivElement>(null);

    const events = useMemo(() => {
        const auditEvents: DiaryEvent[] = monthlyAudits
            .filter(audit => audit.bookedDate && audit.auditor && audit.auditor !== 'Unassigned')
            .map(audit => {
                const site = sites.find(s => s.id === audit.siteId);
                return {
                    id: audit.id,
                    type: 'audit',
                    date: startOfDay(parseISO(audit.bookedDate!)),
                    title: `Audit`,
                    details: `Status: ${audit.status}${audit.bookedTime ? ` at ${audit.bookedTime}`: ''}`,
                    site: site?.name || 'Unknown Site',
                    notes: audit.score ? `Score: ${audit.score}%` : undefined,
                    assignee: audit.auditor,
                    raw: audit,
                };
            });

        const expandedAppointments: DiaryEvent[] = [];
        appointments.forEach(app => {
            const startDate = startOfDay(parseISO(app.date));

            if (!app.recurrence || app.recurrence === 'none') {
                expandedAppointments.push({
                    id: app.id,
                    type: 'appointment',
                    date: startDate,
                    title: app.title,
                    details: `${app.startTime || ''}${app.endTime ? ` - ${app.endTime}` : ''}`,
                    site: app.site,
                    notes: app.notes,
                    assignee: app.assignee,
                    raw: app,
                });
                return;
            }

            const recurrenceEndDate = app.recurrenceEndDate ? startOfDay(parseISO(app.recurrenceEndDate)) : addYears(startDate, 1);
            let currentDate = new Date(startDate.getTime());

            // Limit expansion to prevent infinite loops or massive memory usage
            let safetyCounter = 0;
            while (currentDate <= recurrenceEndDate && safetyCounter < 1000) {
                expandedAppointments.push({
                    id: `${app.id}-${format(currentDate, 'yyyy-MM-dd')}`,
                    type: 'appointment',
                    date: new Date(currentDate.getTime()),
                    title: `${app.title} (Recurring)`,
                    details: `${app.startTime || ''}${app.endTime ? ` - ${app.endTime}` : ''}`,
                    site: app.site,
                    notes: app.notes,
                    assignee: app.assignee,
                    raw: app,
                });

                if (app.recurrence === 'daily') {
                    currentDate = addDays(currentDate, 1);
                } else if (app.recurrence === 'weekly') {
                    currentDate = addWeeks(currentDate, 1);
                } else if (app.recurrence === 'monthly') {
                    currentDate = addMonths(currentDate, 1);
                } else {
                    break;
                }
                safetyCounter++;
            }
        });
        
        const coverEvents: DiaryEvent[] = leave.flatMap(leaveItem => {
            return (leaveItem.coverAssignments || []).map(assignment => {
                const shift = schedule.find(s => s.site === assignment.site && s.cleaner === leaveItem.cleanerName);
                return {
                    id: `${leaveItem.id}-${assignment.site}`,
                    type: 'cover' as const,
                    date: startOfDay(parseISO(leaveItem.date)),
                    title: `Cover shift`,
                    details: `Covering for ${leaveItem.cleanerName}${shift ? ` from ${shift.start} to ${shift.finish}` : ''}`,
                    site: assignment.site,
                    notes: `Original leave type: ${leaveItem.type}`,
                    assignee: assignment.coverCleanerName,
                    raw: { ...leaveItem, site: assignment.site },
                };
            });
        });

        const allEvents = [...auditEvents, ...expandedAppointments, ...coverEvents];
        
        if (!filterStartDate || !filterEndDate) {
            return allEvents.sort((a, b) => a.date.getTime() - b.date.getTime());
        }
        
        const fromDate = startOfDay(parseISO(filterStartDate));
        const toDate = new Date(parseISO(filterEndDate).getTime());
        toDate.setHours(23, 59, 59, 999);

        return allEvents.filter(event => event.date >= fromDate && event.date <= toDate).sort((a, b) => a.date.getTime() - b.date.getTime());

    }, [monthlyAudits, appointments, sites, leave, schedule, filterStartDate, filterEndDate]);

    const managerEvents = useMemo(() => events.filter(e => e.assignee === 'Manager'), [events]);
    const supervisorEvents = useMemo(() => events.filter(e => e.assignee === 'Supervisor'), [events]);
    const mobileCleanerEvents = useMemo(() => events.filter(e => e.assignee === 'Mobile Cleaner'), [events]);
    const staffCoverEvents = useMemo(() => events.filter(e => e.type === 'cover' && e.assignee !== 'Mobile Cleaner'), [events]);

    const handleSaveAppointment = (data: Omit<Appointment, 'id'> | (Partial<Omit<Appointment, 'id'>> & { id: string })) => {
        if ('id' in data) {
            const { id, ...updateData } = data;
            onUpdateAppointment(id, updateData);
        } else {
            onAddAppointment(data);
        }
    };
    
    const eventsForPdf = 
        activeDiary === 'Manager' ? managerEvents :
        activeDiary === 'Supervisor' ? supervisorEvents :
        activeDiary === 'Mobile Cleaner' ? mobileCleanerEvents :
        activeDiary === 'Staff Cover' ? staffCoverEvents :
        [];

    const diaryTitleForPdf = activeDiary === 'Staff Cover' ? 'Staff Cover Diary' : `Diary for ${activeDiary}`;
    
    const handleShareOnWhatsApp = () => {
        const eventsToShare = eventsForPdf;
        const isStaffCoverView = activeDiary === 'Staff Cover';

        let message = `*${diaryTitleForPdf}*\n`;
        message += `Date Range: ${format(parseISO(filterStartDate), 'PPP')} to ${format(parseISO(filterEndDate), 'PPP')}\n\n`;

        const groupedEvents = eventsToShare.reduce((acc, event) => {
            const day = format(event.date, 'yyyy-MM-dd');
            if (!acc[day]) acc[day] = [];
            acc[day].push(event);
            return acc;
        }, {} as Record<string, DiaryEvent[]>);
        const sortedDays = Object.keys(groupedEvents).sort();

        if (sortedDays.length > 0) {
            sortedDays.forEach(day => {
                message += `*${format(parseISO(day), 'EEEE, do MMMM yyyy')}*\n`;
                groupedEvents[day].forEach(event => {
                    message += ` - ${event.title}${event.site ? ` @ ${event.site}` : ''}\n`;
                    message += `   _(${event.details})_\n`;
                    if(isStaffCoverView){
                        message += `   *Covered by: ${event.assignee}*\n`
                    }
                });
                message += "\n";
            });
        } else {
            message += "No events scheduled for this period.";
        }

        const whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
        window.open(whatsappUrl, '_blank');
    };
    
    const handleGeneratePdf = async () => {
      if (!printableRef.current) return;
      setIsGeneratingPdf(true);
  
      try {
        const { default: jsPDF } = await import('jspdf');
        const { default: html2canvas } = await import('html2canvas');
        
        const canvas = await html2canvas(printableRef.current, { scale: 2 });
        const imgData = canvas.toDataURL('image/png');
  
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
  
        const canvasWidth = canvas.width;
        const canvasHeight = canvas.height;
        const ratio = canvasWidth / canvasHeight;
        
        let imgWidthInPdf = pdfWidth - 20;
        let imgHeightInPdf = imgWidthInPdf / ratio;
        
        if (imgHeightInPdf > pdfHeight - 20) {
          imgHeightInPdf = pdfHeight - 20;
          imgWidthInPdf = imgHeightInPdf * ratio;
        }
  
        const x = (pdfWidth - imgWidthInPdf) / 2;
        const y = 10;
  
        pdf.addImage(imgData, 'PNG', x, y, imgWidthInPdf, imgHeightInPdf);
        pdf.save(`Diary_${activeDiary.replace(/\s+/g, '_')}_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  
      } catch (error) {
        console.error("Error generating PDF:", error);
      } finally {
        setIsGeneratingPdf(false);
      }
    };


    const renderEvents = (eventsToRender: DiaryEvent[], isStaffCoverView = false): ReactNode => {
        const groupedEvents = eventsToRender.reduce((acc, event) => {
            const day = format(event.date, 'yyyy-MM-dd');
            if (!acc[day]) acc[day] = [];
            acc[day].push(event);
            return acc;
        }, {} as Record<string, DiaryEvent[]>);
        const sortedDays = Object.keys(groupedEvents).sort();

        if (eventsToRender.length === 0) {
            return (
                <div className="flex items-center justify-center h-48 border-2 border-dashed rounded-lg">
                    <p className="text-muted-foreground text-center">No events scheduled for the selected date range.</p>
                </div>
            )
        }

        return (
            <div className="space-y-6">
                {sortedDays.map(day => (
                    <div key={day}>
                        <h3 className="font-semibold text-lg border-b pb-2 mb-4">{format(parseISO(day), 'EEEE, do MMMM yyyy')}</h3>
                        <div className="space-y-4">
                            {groupedEvents[day].map(event => (
                                <div key={event.id} className="flex items-start gap-4 p-4 rounded-lg border">
                                    <div className={cn("mt-1 flex h-8 w-8 items-center justify-center rounded-full",
                                        event.type === 'audit' ? 'bg-excellerate-blue' :
                                        event.type === 'appointment' ? 'bg-excellerate-teal' :
                                        'bg-excellerate-orange'
                                    )}>
                                        {event.type === 'audit' ? <Briefcase className="h-4 w-4 text-white" /> :
                                         event.type === 'appointment' ? <Calendar className="h-4 w-4 text-white" /> :
                                         <Users className="h-4 w-4 text-white" />
                                        }
                                    </div>
                                    <div className="flex-grow">
                                        <p className="font-semibold">{event.title}{event.site && <span className="font-normal text-muted-foreground"> @ {event.site}</span>}</p>
                                        <p className="text-sm text-muted-foreground">{event.details}</p>
                                        {isStaffCoverView && (
                                            <p className="text-sm font-medium mt-1">Cover provided by: <span className="font-bold">{event.assignee}</span></p>
                                        )}
                                        {event.notes && <p className="text-sm text-muted-foreground mt-1 italic">"{event.notes}"</p>}
                                    </div>
                                    {event.type === 'appointment' && (
                                        <div className="flex items-center gap-1">
                                            <AppointmentDialog sites={sites} onSave={handleSaveAppointment} appointment={event.raw as Appointment}>
                                                <Button variant="ghost" size="icon"><Pencil className="h-4 w-4 text-muted-foreground" /></Button>
                                            </AppointmentDialog>
                                                <AlertDialog>
                                                <AlertDialogTrigger asChild>
                                                    <Button variant="ghost" size="icon"><Trash2 className="h-4 w-4 text-muted-foreground" /></Button>
                                                </AlertDialogTrigger>
                                                <AlertDialogContent>
                                                    <AlertDialogHeader>
                                                        <AlertDialogTitle>Delete Appointment?</AlertDialogTitle>
                                                        <AlertDialogDescription>Are you sure you want to delete "{event.title}"? This will remove the appointment and all its future occurrences. This action cannot be undone.</AlertDialogDescription>
                                                    </AlertDialogHeader>
                                                    <AlertDialogFooter>
                                                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                                                        <AlertDialogAction onClick={() => onRemoveAppointment((event.raw as Appointment).id)}>Delete</AlertDialogAction>
                                                    </AlertDialogFooter>
                                                </AlertDialogContent>
                                            </AlertDialog>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        )
    };
    
    return (
        <>
            <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
                <PrintableDiary events={eventsForPdf} title={diaryTitleForPdf} forwardedRef={printableRef} />
            </div>
            <Card>
                <CardHeader>
                    <div className="flex flex-col sm:flex-row gap-4 sm:items-start sm:justify-between">
                        <div>
                            <CardTitle>Diary</CardTitle>
                            <CardDescription>View upcoming audits and appointments.</CardDescription>
                        </div>
                        <div className="flex gap-2">
                             <Button onClick={handleShareOnWhatsApp} variant="outline">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
                                WhatsApp
                            </Button>
                             <Button onClick={handleGeneratePdf} disabled={isGeneratingPdf} variant="outline">
                                {isGeneratingPdf ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileDown className="mr-2 h-4 w-4" />}
                                {isGeneratingPdf ? 'Generating...' : 'Download PDF'}
                            </Button>
                            {activeDiary !== 'Staff Cover' && (
                                <AppointmentDialog sites={sites} onSave={handleSaveAppointment} defaultAssignee={activeDiary === 'Staff Cover' ? 'Manager' : activeDiary}>
                                    <Button><PlusCircle className="mr-2 h-4 w-4"/> Add Appointment</Button>
                                </AppointmentDialog>
                            )}
                        </div>
                    </div>
                     <div className="pt-4 space-y-2">
                        <Label className="text-sm font-medium">Filter by date</Label>
                        <div className="flex flex-col sm:flex-row items-center gap-2">
                            <Input
                                type="date"
                                value={filterStartDate}
                                onChange={(e) => setFilterStartDate(e.target.value)}
                                className="w-full sm:w-auto"
                            />
                            <span className="text-muted-foreground">to</span>
                            <Input
                                type="date"
                                value={filterEndDate}
                                onChange={(e) => setFilterEndDate(e.target.value)}
                                className="w-full sm:w-auto"
                            />
                        </div>
                    </div>
                </CardHeader>
                <CardContent className="p-0">
                     <Tabs value={activeDiary} onValueChange={setActiveDiary} className="w-full">
                        <div className="border-b">
                            <TabsList className="bg-transparent p-0 m-0 rounded-none gap-4 px-6">
                                <TabsTrigger value="Manager" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Manager's Diary</TabsTrigger>
                                <TabsTrigger value="Supervisor" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Supervisor's Diary</TabsTrigger>
                                <TabsTrigger value="Mobile Cleaner" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Mobile Cleaner's Diary</TabsTrigger>
                                <TabsTrigger value="Staff Cover" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Staff Cover</TabsTrigger>
                            </TabsList>
                        </div>
                        <div className="p-6">
                            <TabsContent value="Manager" className="mt-0">
                                {renderEvents(managerEvents)}
                            </TabsContent>
                            <TabsContent value="Supervisor" className="mt-0">
                                {renderEvents(supervisorEvents)}
                            </TabsContent>
                            <TabsContent value="Mobile Cleaner" className="mt-0">
                                {renderEvents(mobileCleanerEvents)}
                            </TabsContent>
                             <TabsContent value="Staff Cover" className="mt-0">
                                {renderEvents(staffCoverEvents, true)}
                            </TabsContent>
                        </div>
                    </Tabs>
                </CardContent>
            </Card>
        </>
    );
}
