'use client';

import { useState, useMemo, ReactNode, useRef } from 'react';
import type { Site, MonthlyAudit, Appointment, Leave, ScheduleEntry } from '@/lib/data';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { format, parseISO, addDays, addWeeks, addMonths, addYears } from 'date-fns';
import { PlusCircle, Pencil, Trash2, Calendar, Briefcase, FileDown, RefreshCw, Users } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { cn } from '@/lib/utils';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

// Event type for combined view
type DiaryEvent = {
    id: string;
    type: 'audit' | 'appointment' | 'cover';
    date: Date;
    title: string;
    details: string;
    site?: string;
    notes?: string;
    assignee: string;
    raw: Appointment | MonthlyAudit | (Leave & { site: string });
};

type RecurrenceType = 'none' | 'daily' | 'weekly' | 'monthly';

function PrintableDiary({ events, title, forwardedRef }: { events: DiaryEvent[], title: string, forwardedRef: React.Ref<HTMLDivElement> }) {
  const groupedEvents = events.reduce((acc, event) => {
      const day = format(event.date, 'yyyy-MM-dd');
      if (!acc[day]) acc[day] = [];
      acc[day].push(event);
      return acc;
  }, {} as Record<string, DiaryEvent[]>);
  const sortedDays = Object.keys(groupedEvents).sort();

  return (
      <div ref={forwardedRef} className="p-8 bg-white text-black" style={{ width: '794px', minHeight: '1123px' }}>
          <h1 className="text-3xl font-bold mb-2 border-b-2 border-black pb-2">{title}</h1>
          <p className="text-lg mb-6">{format(new Date(), 'PPP')}</p>

          {sortedDays.length > 0 ? sortedDays.map(day => (
              <div key={day} className="mb-6">
                  <h3 className="text-xl font-bold mb-3 border-b border-gray-400 pb-1">{format(parseISO(day), 'EEEE, do MMMM yyyy')}</h3>
                  <div className="space-y-4">
                      {groupedEvents[day].map(event => (
                          <div key={event.id}>
                              <p className="font-semibold text-lg">{event.title}{event.site && ` @ ${event.site}`}</p>
                              <p className="text-gray-700">{event.details}</p>
                              {event.notes && <p className="text-gray-600 italic pl-4">"{event.notes}"</p>}
                          </div>
                      ))}
                  </div>
              </div>
          )) : <p>No events scheduled.</p>}
          
          <div style={{ position: 'absolute', bottom: '20px', left: '20px', right: '20px', textAlign: 'center', fontSize: '10px', color: '#888' }}>
              Report Generated by Excellerate Services
          </div>
      </div>
  );
}


interface AppointmentDialogProps {
  sites: Site[];
  onSave: (data: Omit<Appointment, 'id'> | (Partial<Omit<Appointment, 'id'>> & { id: string })) => void;
  appointment?: Appointment;
  defaultAssignee?: string;
  children: React.ReactNode;
}

function AppointmentDialog({ sites, onSave, appointment, defaultAssignee, children }: AppointmentDialogProps) {
    const [isOpen, setIsOpen] = useState(false);
    const { toast } = useToast();
    
    const [title, setTitle] = useState(appointment?.title || '');
    const [site, setSite] = useState(appointment?.site || '');
    const [date, setDate] = useState<string>('');
    const [assignee, setAssignee] = useState(appointment?.assignee || defaultAssignee || 'Owen Newton');
    const [startTime, setStartTime] = useState(appointment?.startTime || '');
    const [endTime, setEndTime] = useState(appointment?.endTime || '');
    const [notes, setNotes] = useState(appointment?.notes || '');
    const [recurrence, setRecurrence] = useState<RecurrenceType>(appointment?.recurrence || 'none');
    const [recurrenceEndDate, setRecurrenceEndDate] = useState<string>('');

    const handleSave = () => {
        if (!title || !date || !assignee) {
            toast({ variant: 'destructive', title: 'Missing Information', description: 'Please provide a title, date, and assignee.' });
            return;
        }

        if (recurrence !== 'none' && !recurrenceEndDate) {
            toast({ variant: 'destructive', title: 'Missing Information', description: 'Please provide an end date for the recurring appointment.' });
            return;
        }

        const appointmentData = {
            title,
            site: site || undefined,
            date,
            assignee,
            startTime,
            endTime,
            notes,
            recurrence,
            recurrenceEndDate: (recurrence !== 'none' && recurrenceEndDate) ? recurrenceEndDate : undefined
        };

        if (appointment) {
            onSave({ id: appointment.id, ...appointmentData });
        } else {
            onSave(appointmentData);
        }
        
        setIsOpen(false);
    };
    
    const handleOpenChange = (open: boolean) => {
        if (open) {
            setTitle(appointment?.title || '');
            setSite(appointment?.site || '');
            setDate(appointment ? appointment.date : format(new Date(), 'yyyy-MM-dd'));
            setAssignee(appointment?.assignee || defaultAssignee || 'Owen Newton');
            setStartTime(appointment?.startTime || '');
            setEndTime(appointment?.endTime || '');
            setNotes(appointment?.notes || '');
            setRecurrence(appointment?.recurrence || 'none');
            setRecurrenceEndDate(appointment?.recurrenceEndDate || '');
        }
        setIsOpen(open);
    }

    return (
        <Dialog open={isOpen} onOpenChange={handleOpenChange}>
            <DialogTrigger asChild>{children}</DialogTrigger>
            <DialogContent className="sm:max-w-[480px]">
                <DialogHeader><DialogTitle>{appointment ? 'Edit' : 'Add'} Appointment</DialogTitle></DialogHeader>
                <div className="grid gap-4 py-4">
                    <div className="space-y-2">
                        <Label htmlFor="title">Title</Label>
                        <Input id="title" value={title} onChange={e => setTitle(e.target.value)} />
                    </div>
                     <div className="space-y-2">
                        <Label htmlFor="site">Site (Optional)</Label>
                        <Select value={site} onValueChange={setSite}>
                            <SelectTrigger id="site">
                                <SelectValue placeholder="Select a site" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="">None</SelectItem>
                                {sites.map(s => <SelectItem key={s.id} value={s.name}>{s.name}</SelectItem>)}
                            </SelectContent>
                        </Select>
                    </div>
                     <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label htmlFor="date">Date</Label>
                            <Input id="date" type="date" value={date} onChange={e => setDate(e.target.value)} />
                        </div>
                        <div className="space-y-2">
                             <Label htmlFor="assignee">Assign To</Label>
                             <Select value={assignee} onValueChange={setAssignee}>
                                <SelectTrigger id="assignee">
                                    <SelectValue placeholder="Select person" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="Owen Newton">Owen Newton</SelectItem>
                                    <SelectItem value="Nick Miller">Nick Miller</SelectItem>
                                    <SelectItem value="Mircalla Bond (Carla)">Mircalla Bond (Carla)</SelectItem>
                                </SelectContent>
                             </Select>
                        </div>
                    </div>
                     <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label htmlFor="start-time">Start Time</Label>
                            <Input id="start-time" type="time" value={startTime} onChange={e => setStartTime(e.target.value)} />
                        </div>
                        <div className="space-y-2">
                            <Label htmlFor="end-time">End Time</Label>
                            <Input id="end-time" type="time" value={endTime} onChange={e => setEndTime(e.target.value)} />
                        </div>
                    </div>
                     <div className="space-y-2">
                        <Label>Recurrence</Label>
                        <div className="grid grid-cols-2 gap-4">
                             <Select value={recurrence} onValueChange={(v: RecurrenceType) => setRecurrence(v)}>
                                <SelectTrigger>
                                    <SelectValue placeholder="No recurrence" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="none">None</SelectItem>
                                    <SelectItem value="daily">Daily</SelectItem>
                                    <SelectItem value="weekly">Weekly</SelectItem>
                                    <SelectItem value="monthly">Monthly</SelectItem>
                                </SelectContent>
                             </Select>
                             {recurrence !== 'none' && (
                                <Input type="date" value={recurrenceEndDate} onChange={e => setRecurrenceEndDate(e.target.value)} placeholder="End date" />
                             )}
                        </div>
                    </div>
                     <div className="space-y-2">
                        <Label htmlFor="notes">Notes</Label>
                        <Textarea id="notes" value={notes} onChange={e => setNotes(e.target.value)} placeholder="Optional notes..." />
                    </div>
                </div>
                <DialogFooter>
                    <DialogClose asChild><Button variant="ghost">Cancel</Button></DialogClose>
                    <Button onClick={handleSave}>Save</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}

interface DiaryTabProps {
  sites: Site[];
  appointments: Appointment[];
  monthlyAudits: MonthlyAudit[];
  leave: Leave[];
  schedule: ScheduleEntry[];
  onAddAppointment: (data: Omit<Appointment, 'id'>) => void;
  onUpdateAppointment: (id: string, data: Partial<Omit<Appointment, 'id'>>) => void;
  onRemoveAppointment: (id: string) => void;
}

export default function DiaryTab({ sites, appointments, monthlyAudits, leave, schedule, onAddAppointment, onUpdateAppointment, onRemoveAppointment }: DiaryTabProps) {
    const [filterStartDate, setFilterStartDate] = useState<string>(format(new Date(), 'yyyy-MM-dd'));
    const [filterEndDate, setFilterEndDate] = useState<string>(format(new Date(), 'yyyy-MM-dd'));
    const [activeDiary, setActiveDiary] = useState('Owen Newton');
    const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
    const printableRef = useRef<HTMLDivElement>(null);

    const events = useMemo(() => {
        const auditEvents: DiaryEvent[] = monthlyAudits
            .filter(audit => audit.bookedDate && audit.auditor && audit.auditor !== 'Unassigned')
            .map(audit => {
                const site = sites.find(s => s.id === audit.siteId);
                return {
                    id: audit.id,
                    type: 'audit',
                    date: parseISO(audit.bookedDate!),
                    title: `Audit`,
                    details: `Status: ${audit.status}${audit.bookedTime ? ` at ${audit.bookedTime}`: ''}`,
                    site: site?.name || 'Unknown Site',
                    notes: audit.score ? `Score: ${audit.score}%` : undefined,
                    assignee: audit.auditor,
                    raw: audit,
                };
            });

        const expandedAppointments: DiaryEvent[] = [];
        appointments.forEach(app => {
            const startDate = parseISO(app.date);

            if (!app.recurrence || app.recurrence === 'none') {
                expandedAppointments.push({
                    id: app.id,
                    type: 'appointment',
                    date: startDate,
                    title: app.title,
                    details: `${app.startTime || ''}${app.endTime ? ` - ${app.endTime}` : ''}`,
                    site: app.site,
                    notes: app.notes,
                    assignee: app.assignee,
                    raw: app,
                });
                return;
            }

            const recurrenceEndDate = app.recurrenceEndDate ? parseISO(app.recurrenceEndDate) : addYears(startDate, 1);
            let currentDate = startDate;

            while (currentDate <= recurrenceEndDate) {
                expandedAppointments.push({
                    id: `${app.id}-${format(currentDate, 'yyyy-MM-dd')}`,
                    type: 'appointment',
                    date: currentDate,
                    title: `${app.title} (Recurring)`,
                    details: `${app.startTime || ''}${app.endTime ? ` - ${app.endTime}` : ''}`,
                    site: app.site,
                    notes: app.notes,
                    assignee: app.assignee,
                    raw: app,
                });

                if (app.recurrence === 'daily') {
                    currentDate = addDays(currentDate, 1);
                } else if (app.recurrence === 'weekly') {
                    currentDate = addWeeks(currentDate, 1);
                } else if (app.recurrence === 'monthly') {
                    currentDate = addMonths(currentDate, 1);
                } else {
                    break;
                }
            }
        });
        
        const coverEvents: DiaryEvent[] = leave.flatMap(leaveItem => {
            return (leaveItem.coverAssignments || []).map(assignment => {
                const shift = schedule.find(s => s.site === assignment.site && s.cleaner === leaveItem.cleanerName);
                return {
                    id: `${leaveItem.id}-${assignment.site}`,
                    type: 'cover' as const,
                    date: parseISO(leaveItem.date),
                    title: `Cover shift`,
                    details: `Covering for ${leaveItem.cleanerName}${shift ? ` from ${shift.start} to ${shift.finish}` : ''}`,
                    site: assignment.site,
                    notes: `Original leave type: ${leaveItem.type}`,
                    assignee: assignment.coverCleanerName,
                    raw: { ...leaveItem, site: assignment.site },
                };
            });
        });

        const allEvents = [...auditEvents, ...expandedAppointments, ...coverEvents];
        
        if (!filterStartDate || !filterEndDate) {
            return allEvents.sort((a, b) => a.date.getTime() - b.date.getTime());
        }
        
        const fromDate = parseISO(filterStartDate);
        fromDate.setHours(0,0,0,0);
        const toDate = parseISO(filterEndDate);
        toDate.setHours(23, 59, 59, 999);

        return allEvents.filter(event => event.date >= fromDate && event.date <= toDate).sort((a, b) => a.date.getTime() - b.date.getTime());

    }, [monthlyAudits, appointments, sites, leave, schedule, filterStartDate, filterEndDate]);

    const owenEvents = useMemo(() => events.filter(e => e.assignee === 'Owen Newton'), [events]);
    const nickEvents = useMemo(() => events.filter(e => e.assignee === 'Nick Miller'), [events]);
    const carlaEvents = useMemo(() => events.filter(e => e.assignee === 'Mircalla Bond (Carla)'), [events]);
    const staffCoverEvents = useMemo(() => events.filter(e => e.type === 'cover' && e.assignee !== 'Mircalla Bond (Carla)'), [events]);

    const handleSaveAppointment = (data: Omit<Appointment, 'id'> | (Partial<Omit<Appointment, 'id'>> & { id: string })) => {
        if ('id' in data) {
            const { id, ...updateData } = data;
            onUpdateAppointment(id, updateData);
        } else {
            onAddAppointment(data);
        }
    };
    
    const handleGeneratePdf = async () => {
      if (!printableRef.current) return;
      setIsGeneratingPdf(true);
  
      try {
        const { default: jsPDF } = await import('jspdf');
        const { default: html2canvas } = await import('html2canvas');
        
        const canvas = await html2canvas(printableRef.current, { scale: 2 });
        const imgData = canvas.toDataURL('image/png');
  
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
  
        const canvasWidth = canvas.width;
        const canvasHeight = canvas.height;
        const ratio = canvasWidth / canvasHeight;
        
        let imgWidthInPdf = pdfWidth - 20;
        let imgHeightInPdf = imgWidthInPdf / ratio;
        
        if (imgHeightInPdf > pdfHeight - 20) {
          imgHeightInPdf = pdfHeight - 20;
          imgWidthInPdf = imgHeightInPdf * ratio;
        }
  
        const x = (pdfWidth - imgWidthInPdf) / 2;
        const y = 10;
  
        pdf.addImage(imgData, 'PNG', x, y, imgWidthInPdf, imgHeightInPdf);
        pdf.save(`Diary_${activeDiary.replace(/\s+/g, '_')}_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  
      } catch (error) {
        console.error("Error generating PDF:", error);
      } finally {
        setIsGeneratingPdf(false);
      }
    };


    const renderEvents = (eventsToRender: DiaryEvent[], isStaffCoverView = false): ReactNode => {
        const groupedEvents = eventsToRender.reduce((acc, event) => {
            const day = format(event.date, 'yyyy-MM-dd');
            if (!acc[day]) acc[day] = [];
            acc[day].push(event);
            return acc;
        }, {} as Record<string, DiaryEvent[]>);
        const sortedDays = Object.keys(groupedEvents).sort();

        if (eventsToRender.length === 0) {
            return (
                <div className="flex items-center justify-center h-48 border-2 border-dashed rounded-lg">
                    <p className="text-muted-foreground text-center">No events scheduled for the selected date range.</p>
                </div>
            )
        }

        return (
            <div className="space-y-6">
                {sortedDays.map(day => (
                    <div key={day}>
                        <h3 className="font-semibold text-lg border-b pb-2 mb-4">{format(parseISO(day), 'EEEE, do MMMM yyyy')}</h3>
                        <div className="space-y-4">
                            {groupedEvents[day].map(event => (
                                <div key={event.id} className="flex items-start gap-4 p-4 rounded-lg border">
                                    <div className={cn("mt-1 flex h-8 w-8 items-center justify-center rounded-full",
                                        event.type === 'audit' ? 'bg-excellerate-blue' :
                                        event.type === 'appointment' ? 'bg-excellerate-teal' :
                                        'bg-excellerate-orange'
                                    )}>
                                        {event.type === 'audit' ? <Briefcase className="h-4 w-4 text-white" /> :
                                         event.type === 'appointment' ? <Calendar className="h-4 w-4 text-white" /> :
                                         <Users className="h-4 w-4 text-white" />
                                        }
                                    </div>
                                    <div className="flex-grow">
                                        <p className="font-semibold">{event.title}{event.site && <span className="font-normal text-muted-foreground"> @ {event.site}</span>}</p>
                                        <p className="text-sm text-muted-foreground">{event.details}</p>
                                        {isStaffCoverView && (
                                            <p className="text-sm font-medium mt-1">Cover provided by: <span className="font-bold">{event.assignee}</span></p>
                                        )}
                                        {event.notes && <p className="text-sm text-muted-foreground mt-1 italic">"{event.notes}"</p>}
                                    </div>
                                    {event.type === 'appointment' && (
                                        <div className="flex items-center gap-1">
                                            <AppointmentDialog sites={sites} onSave={handleSaveAppointment} appointment={event.raw as Appointment}>
                                                <Button variant="ghost" size="icon"><Pencil className="h-4 w-4 text-muted-foreground" /></Button>
                                            </AppointmentDialog>
                                                <AlertDialog>
                                                <AlertDialogTrigger asChild>
                                                    <Button variant="ghost" size="icon"><Trash2 className="h-4 w-4 text-muted-foreground" /></Button>
                                                </AlertDialogTrigger>
                                                <AlertDialogContent>
                                                    <AlertDialogHeader>
                                                        <AlertDialogTitle>Delete Appointment?</AlertDialogTitle>
                                                        <AlertDialogDescription>Are you sure you want to delete "{event.title}"? This will remove the appointment and all its future occurrences. This action cannot be undone.</AlertDialogDescription>
                                                    </AlertDialogHeader>
                                                    <AlertDialogFooter>
                                                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                                                        <AlertDialogAction onClick={() => onRemoveAppointment((event.raw as Appointment).id)}>Delete</AlertDialogAction>
                                                    </AlertDialogFooter>
                                                </AlertDialogContent>
                                            </AlertDialog>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        )
    };
    
    const eventsForPdf = 
        activeDiary === 'Owen Newton' ? owenEvents :
        activeDiary === 'Nick Miller' ? nickEvents :
        activeDiary === 'Mircalla Bond (Carla)' ? carlaEvents :
        activeDiary === 'Staff Cover' ? staffCoverEvents :
        [];

    const diaryTitleForPdf = activeDiary === 'Staff Cover' ? 'Staff Cover Diary' : `Diary for ${activeDiary}`;

    return (
        <>
            <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
                <PrintableDiary events={eventsForPdf} title={diaryTitleForPdf} forwardedRef={printableRef} />
            </div>
            <Card>
                <CardHeader>
                    <div className="flex flex-col sm:flex-row gap-4 sm:items-start sm:justify-between">
                        <div>
                            <CardTitle>Diary</CardTitle>
                            <CardDescription>View upcoming audits and appointments.</CardDescription>
                        </div>
                        <div className="flex gap-2">
                             <Button onClick={handleGeneratePdf} disabled={isGeneratingPdf} variant="outline">
                                {isGeneratingPdf ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <FileDown className="mr-2 h-4 w-4" />}
                                {isGeneratingPdf ? 'Generating...' : 'Download PDF'}
                            </Button>
                            {activeDiary !== 'Staff Cover' && (
                                <AppointmentDialog sites={sites} onSave={handleSaveAppointment} defaultAssignee={activeDiary === 'Staff Cover' ? 'Owen Newton' : activeDiary}>
                                    <Button><PlusCircle className="mr-2 h-4 w-4"/> Add Appointment</Button>
                                </AppointmentDialog>
                            )}
                        </div>
                    </div>
                     <div className="pt-4 space-y-2">
                        <Label className="text-sm font-medium">Filter by date</Label>
                        <div className="flex flex-col sm:flex-row items-center gap-2">
                            <Input
                                type="date"
                                value={filterStartDate}
                                onChange={(e) => setFilterStartDate(e.target.value)}
                                className="w-full sm:w-auto"
                            />
                            <span className="text-muted-foreground">to</span>
                            <Input
                                type="date"
                                value={filterEndDate}
                                onChange={(e) => setFilterEndDate(e.target.value)}
                                className="w-full sm:w-auto"
                            />
                        </div>
                    </div>
                </CardHeader>
                <CardContent className="p-0">
                     <Tabs value={activeDiary} onValueChange={setActiveDiary} className="w-full">
                        <div className="border-b">
                            <TabsList className="bg-transparent p-0 m-0 rounded-none gap-4 px-6">
                                <TabsTrigger value="Owen Newton" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Owen's Diary</TabsTrigger>
                                <TabsTrigger value="Nick Miller" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Nick's Diary</TabsTrigger>
                                <TabsTrigger value="Mircalla Bond (Carla)" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Carla's Diary</TabsTrigger>
                                <TabsTrigger value="Staff Cover" className="data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none">Staff Cover</TabsTrigger>
                            </TabsList>
                        </div>
                        <div className="p-6">
                            <TabsContent value="Owen Newton" className="mt-0">
                                {renderEvents(owenEvents)}
                            </TabsContent>
                            <TabsContent value="Nick Miller" className="mt-0">
                                {renderEvents(nickEvents)}
                            </TabsContent>
                            <TabsContent value="Mircalla Bond (Carla)" className="mt-0">
                                {renderEvents(carlaEvents)}
                            </TabsContent>
                             <TabsContent value="Staff Cover" className="mt-0">
                                {renderEvents(staffCoverEvents, true)}
                            </TabsContent>
                        </div>
                    </Tabs>
                </CardContent>
            </Card>
        </>
    );
}
